### PR TITLE
Register task output files

### PR DESCRIPTION
**Pull request by jberkel**
This allows task chaining in the form of:

```gradle
task downloadFiles(type: Download)  {
  src(["http://foo.com/1", "http://foo.com/2"])
  dest(file('downloads'))
}

task processFiles {
  inputs.files downloadFiles
}
```

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Nice! Thank you!

I'll have a look at the pull request during the week and get back to you if necessary.

**Comment by jberkel** [comment]
Any comments on this? One thing which occurred to me is that up-to-date checking might need to be refined. When registering output files gradle will just skip the execution of the task if the files are present.

**Comment by michel-kraemer** [comment]
> When registering output files gradle will just skip the execution of the task if the files are present.

This is interesting. I have no experience with this. If you have an idea how to implement it please update the PR. Thanks!

**Comment by jberkel** [comment]
I think this is finally ready to be reviewed now.

**Comment by michel-kraemer** [comment]
Thank you so much. Very good work and very thorough tests as usual! 👍

**Comment by jberkel** [comment]
You're welcome! Do you publish snapshot builds off the master branch? I have a project which depends on this feature, and I'd like to have it integrated without too much hassle.

**Comment by michel-kraemer** [comment]
Yes, I publish snapshots from time to time, but you can wait for the release in this case. I'll do it tomorrow.

**Pull request merged**
