### PR TITLE
Respect "http.nonProxyHosts"

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Thanks for the new pull request. What's the difference between this one and the earlier one? The build fails on the CI server. Could you try to fix it please? Thanks.

**Comment by Ithildir** [comment]
Hi,
The only change is in the tests: if `localhost.localdomain` can't be found, it uses [this](https://github.com/michel-kraemer/gradle-download-task/pull/72/files#diff-c8f9d17068f8b666e3e4cc8ea4dfeee0R141).

For some reasons, the CI tests don't run:

```
update-alternatives --set java /usr/lib/jvm/jdk1.7.0/bin/java
update-alternatives --set javac /usr/lib/jvm/jdk1.7.0/bin/javac
update-alternatives: error: alternative /usr/lib/jvm/jdk1.7.0/bin/java for java not registered; not setting
update-alternatives: error: alternative /usr/lib/jvm/jdk1.7.0/bin/javac for javac not registered; not setting

update-alternatives --set java /usr/lib/jvm/jdk1.7.0/bin/java
update-alternatives --set javac /usr/lib/jvm/jdk1.7.0/bin/javac
 returned exit code 2

Action failed: Setting Java version to Oracle 7
```

Do CI tests work for you?

**Comment by michel-kraemer** [comment]
I tested this PR locally and it works well. It seems the CI server had temporary problems. I will merge the PR and see if everything works as expected again.

**Comment by michel-kraemer** [comment]
OK. It seems to work well. Thanks a lot for the contribution!

**Pull request merged**
