### PR TITLE
Add  flag to allow ignoring certs

### LINKED ISSUE #23: Allow customization of SSL client verification
It would be really useful to have one or more of the following for dealing with non-public certificates (which often come up in corporate environments):
* specifying a trust store
* turning off host verification

### PR DESCRIPTION
**Pull request by punya**
Closes #23

[Review on Reviewable](https://reviewable.io/reviews/michel-kraemer/gradle-download-task/24)

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Looks great. I will merge as soon as possible (maybe on the weekend?)

Michel

**Comment by punya** [comment]
Thanks!

**Comment by punya** [comment]
Hi @michel-kraemer, please let me know if I can do anything further to get this merged :smile:

**Comment by michel-kraemer** [comment]
Sorry. I'm just too busy. I'll get back to you as soon as I can.

Cheers,
Michel

**Comment by punya** [comment]
Sorry to bug you about this again, but did you have any luck finding more time? Can I help in any way?

**Comment by Augi** [comment]
:+1:

**Comment by Augi** [comment]
If it helps, I also reviewed the code and looks OK.

**Comment by michel-kraemer** [comment]
@punya  Thanks for the PR. I will merge it right now. I will, however, rename `insecure` to `acceptAnyCertificate` because 'insecure' is too generic in my opinion.

@Augi Thanks for the review!

**Comment by michel-kraemer** [comment]
Sorry again for the long delay!

**Comment by Augi** [comment]
Cool, thanks! When do you plan to release a new version of the plugin, please?

**Comment by punya** [comment]
Thanks for fixing and merging my PR! I look forward to the release.

**Comment by michel-kraemer** [comment]
@Augi I want to fix issue #25 first and also have a look at #22 at least. Then I can release the new version. If you have any ideas for either of them then this would speed up the process. Thanks.

**Pull request merged**
