### PR TITLE
Fix If-Modified-Since handling

### PR DESCRIPTION
**Pull request by jberkel**
I started to work on #43 again, but I keep finding those distracting bugs :)

### CODE REVIEW

**Comment by jberkel** [comment]
On a side note, are redirects handled properly currently?

**Comment by michel-kraemer** [comment]
Thanks a lot for your on-going contributions! I really appreciate that. I recently migrated to Apache HttpClient so that must be the reason why there are still so many bugs. Sorry for that! I thought I had unit tests for everything but it seems they were not thorough enough.

I'm currently out of office (with limited Internet connectivity actually), so I cannot look into your PR in detail. Can you please quickly elaborate what the problem was that you fixed?

> On a side note, are redirects handled properly currently?
I guess so. There should be a unit test for it.

**Comment by jberkel** [comment]
This PR fixes two things:

 * the "If-Modified-Since" header in the outgoing request was malformed (timestamps vs. HTTP date string)
 * a HTTP 304 (not modified) response from the server got treated as error

I haven't looked at the unit tests in detail yet, but it should be possible to test everything properly even without the functional tests. Maybe code coverage could help give a rough indication of what's missing there.

What was the reason for replacing HttpURLConnection?

**Comment by u3r** [comment]
HttpURLConnection was ditched because of the poor support for authenticated proxies - see #41.

**Comment by michel-kraemer** [comment]
Thanks a lot for the pull request. Very good work!

**Pull request merged**
