### PR TITLE
Fix for #53 - Support verification via md5 checksum file

### PR DESCRIPTION
**Pull request by skundrik**

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Thanks for the PR. Looks like an interesting idea. May I ask you to fix the unit tests please, so I can merge it? Thanks!

**Comment by skundrik** [comment]
This should be good to go now

**Comment by michel-kraemer** [comment]
As I said earlier, this is a very nice idea. I'd really like to see this in gradle-download-task. Thanks a lot for your contribution!

It seems there is no standardised format for checksum files. See the following files for example:
http://www.apache.org/dist/spark/spark-1.6.2/

AFAICT the code you propose won't work with these files. In addition, your code trims the files at 32 bytes. What about checksums longer than 256 bits?

Any idea how to get to a more generic solution? As I said, I would love to see this in gradle-download-task, but I'd hate to promise something in the README that only works in certain cases.

Cheers,
Michel

**Comment by skundrik** [comment]
Hmm, I see your point. I'll try to find some "spec" for those but it might take a while. Feel free to let me know if you come across some info.

**Comment by skundrik** [comment]
Had a closer look and I can't find any other project that would have a similar format to spark. In fact all the projects I looked at seem to have the MD5 hash as the first 32 bytes.

**Comment by michel-kraemer** [comment]
Yes, you're right. Thanks for your engagement. I found the following link. It's an interesting read:
https://www.openoffice.org/download/checksums.html

I think we should implement it so it's compatible to existing tools and clearly mention this in the docs.

**Comment by skundrik** [comment]
I have added the implementation to support the gpg file format, added some more tests and updated the docs. Please have a look.

**Comment by michel-kraemer** [comment]
Thanks. You pushed a lot of commits. I'll need some time to review them. I'll do this tomorrow and get back to you.

**Comment by michel-kraemer** [comment]
OK. I took a quick look and saw that there's actually not very much code to review. It looks much more because there are so many commits. :-)

I really like your code. It's almost ready to be merged. Thank you so much. 👍 

There are a couple of things I'd like to comment or improve. Could you please squash your commits? If you rebase against master and put your commits after mine the diff here on GitHub will also be a lot smaller and easier to read. Thanks!

**Comment by michel-kraemer** [comment]
Bump. :-)

**Comment by skundrik** [comment]
Sorry Michel, just didn't have any time to work on it. I haven't abandoned it ;-) . I'll see if I can squirrel some time over the next couple of weeks.

**Comment by michel-kraemer** [comment]
Bump. :wink:

**Comment by michel-kraemer** [comment]
I'm closing this because there was no response from the original poster and because it has conflicts with the master branch. If you wish to continue working on this, feel free to open the PR again.

**Pull request closed without merging**
