### PR TITLE
Add provider support and cleanup gradle version checking

### PR DESCRIPTION
**Pull request by Sineaggi**
Add support for `RegularFile`, `Directory`, and `ProjectLayout` apis. Also cleans up `Provider<>` support.
Example usages:
```kotlin
val downloadOpenJDK = tasks.register("downloadOpenJDK", Download::class) {
    src("https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz")
    dest(layout.buildDirectory.file("download/openjdk-14.0.2_linux-x64_bin.tar.gz"))
    // or
    dest(layout.buildDirectory.dir("download"))
    useETag("all")
    overwrite(false)
}
```

### CODE REVIEW

**Comment by Sineaggi** [comment]
Currently the download task does not support downloading to directories (other than the build directory).

**Comment by Sineaggi** [comment]
A workaround for not supporting `ProjectLayout` and `RegularFile`s directly can be seen below
```kotlin
val downloadOpenJDK = tasks.register("downloadOpenJDK", Download::class) {
    src("https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz")
    dest(layout.buildDirectory.file("download/openjdk-14.0.2_linux-x64_bin.tar.gz").map { it.asFile })
    useETag("all")
    overwrite(false)
}

val verifyOpenJDK = tasks.register("verifyOpenJDK", Verify::class) {
    src(layout.buildDirectory.file("download/openjdk-14.0.2_linux-x64_bin.tar.gz").map { it.asFile })
    dependsOn(downloadOpenJDK)
    algorithm("SHA-256")
    checksum("91310200f072045dc6cef2c8c23e7e6387b37c46e9de49623ce0fa461a24623d")
}
```

**Comment by michel-kraemer** [comment]
Nice work! Thank you so much.

Just a few notes though:
* Why did you remove the `ProviderHelper`? Now, you need to compare the Gradle version over and over again. IMHO this is bad style.
* Could you try to maintain the code coverage? Or at least investigate why it was reduced?

Thanks!

**Comment by Sineaggi** [comment]
@michel-kraemer I can absolutely check out the code coverage. I did start with a set of helper classes (check out the first commit and let me know if you prefer it). I simply thought that checking the gradle version multiple times ended up with cleaner code overall, even if it made it a bit noisier.

**Pull request merged**
