### PR TITLE
Respect http.nonProxyHosts

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Hi Ithildir!

Thank you so much for the pull request. It looks really good. I will definitely merge it.

I found a small issue though. The `nonProxyHosts` tests still runs through even if I set the parameter `newNonProxyHosts` to `localhost2` or something else. The reason for this is that the JRE automatically bypasses `localhost` as a proxy (see the `findNonProxyHosts` method).

Any idea how to improve this?

Thanks!
Michel

**Comment by Ithildir** [comment]
Hi Michel!

I force-pushed a possible workaround that I found on http://bugs.java.com/view_bug.do?bug_id=6737819: instead of calling `localhost`, I always call `localhost.localdomain`, so the default nonProxyHosts won't get in the way.

What do you think? :blush:

**Comment by michel-kraemer** [comment]
Sounds good to me. I'll review it as soon as possible.

**Comment by Ithildir** [comment]
Thank you! :blush:

**Comment by michel-kraemer** [comment]
I'm sorry, but I get the following exception when I try your code:

```
Caused by: java.net.UnknownHostException: localhost.localdomain
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:883)
	at java.net.InetAddress.getAddressFromNameService(InetAddress.java:1236)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1187)
	at java.net.InetAddress.getAllByName(InetAddress.java:1117)
	at java.net.InetAddress.getAllByName(InetAddress.java:1053)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at de.undercouch.gradle.tasks.download.DownloadAction.openConnection(DownloadAction.java:411)
	at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:195)
	at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:144)
	at de.undercouch.gradle.tasks.download.Download.download(Download.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	... 45 more
```

I'm on OS X El Capitan. I tested it with Java 6 and Java 7. If I remember correctly this is the reason why I implemented  the `findNonProxyHosts()` method in the first place. I had the same problem under Windows by the way.

You could argue that it's just the unit tests that are failing but I think it's important that they work correctly on all systems to allow other contributors to execute them on their machines.

It's a shame the PR cannot be merged yet. It's good code. I'll try to look for a different solution. If you find something in the meantime please let me know.

As a last resort we may have to disable the `nonProxyHosts()` test so that the others can be executed correctly at least.

**Pull request closed without merging**
